export const SELECT_COMPANY = 'SELECT_COMPANY';
export const DESELECT_COMPANY = 'DESELECT_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const MERGE_SELECTED_COMPANIES = 'MERGE_SELECTED_COMPANIES';
